import React, { useState, useEffect } from "react";
import { useParams, useNavigate, Link } from "react-router-dom";
import { bharat01 } from "@/api/bharat01Client";
import { NATION } from "@/lib/bharatStates";
import { getNationalResults } from "@/lib/electionResults";
import ParliamentChamber from "@/components/parliament/ParliamentChamber";
import ParliamentFloor from "@/components/parliament/ParliamentFloor";
import BillVotePanel from "@/components/parliament/BillVotePanel";
import { ArrowLeft, Landmark, Briefcase, Crown } from "lucide-react";

// National parliament session — round-table chamber with Speaker, live chat,
// motion voting and bill voting. The chamber is generated by the admin
// (Admin → Parliament) after the election is won and government formation is ready.

export default function ParliamentSession() {
  const { house } = useParams();
  const navigate = useNavigate();
  const isLok = house === "lok-sabha";
  // Rajya Sabha is a national, view-only house — no floor chat, motions or govt sections.
  const isRajya = house === "rajya-sabha";
  const [loading, setLoading] = useState(true);
  const [setup, setSetup] = useState(null);
  const [selectedSeat, setSelectedSeat] = useState(null);
  const [winners, setWinners] = useState([]);
  const [ministers, setMinisters] = useState([]);

  useEffect(() => { load(); }, []);

  async function load() {
    setLoading(true);
    try {
      const setups = await bharat01.entities.ParliamentSetup.filter({ scope: "national" }, "-created_date", 10);
      setSetup(setups[0] || null);
    } catch (e) { setSetup(null); }
    if (isLok) {
      try {
        const { winners: w } = await getNationalResults();
        setWinners(w);
      } catch (e) { setWinners([]); }
      try {
        setMinisters(await bharat01.entities.Minister.filter({ scope: "national", is_active: true }));
      } catch (e) { setMinisters([]); }
    }
    setLoading(false);
  }

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-screen bg-zinc-950">
        <div className="w-10 h-10 border-4 border-orange-500/30 border-t-orange-500 rounded-full animate-spin" />
      </div>
    );
  }

  const partySeats = Object.entries(winners.reduce((acc, w) => {
    const p = w.party_name || "Independent";
    acc[p] = (acc[p] || 0) + 1;
    return acc;
  }, {})).map(([party, count]) => ({ party, count }));

  return (
    <div className="p-4 max-w-lg mx-auto pb-20">
      {!isRajya && (
        <div className="flex items-center justify-end mb-3">
          <Link to="/government"
            className="text-[11px] bg-gradient-to-r from-orange-500 to-amber-500 text-white font-bold px-3 py-1.5 rounded-full flex items-center gap-1">
            <Briefcase className="w-3.5 h-3.5" /> Full Govt Dashboard
          </Link>
        </div>
      )}

      <div className="flex items-center gap-2 mb-1">
        {isLok ? <Landmark className="w-6 h-6 text-amber-400" /> : <Crown className="w-6 h-6 text-amber-400" />}
        <h1 className="text-2xl font-bold text-white">{isLok ? "Lok Sabha" : "Rajya Sabha"}</h1>
      </div>
      <p className="text-xs text-zinc-500 mb-4">{NATION.name} · National Parliament</p>

      {setup ? (
        <>
          <ParliamentChamber setup={setup} selectedSeat={isRajya ? null : selectedSeat} onSeatClick={isRajya ? undefined : setSelectedSeat}
            winners={isRajya ? [] : winners} ministers={isRajya ? [] : ministers} memberLabel="MP" />
          {isRajya ? (
            <p className="text-[11px] text-zinc-500 text-center bg-zinc-900 rounded-xl p-3 border border-zinc-800">
              Rajya Sabha is a view-only house — debates, motions and voting happen in the Lok Sabha.
            </p>
          ) : (
            <>
              <ParliamentFloor channelKey="national" speakerName={ministers.find(m => m.position === "speaker")?.player_name || setup.speaker_name} totalSeats={setup.total_seats} selectedSeat={selectedSeat} partySeats={partySeats} winners={winners} memberLabel="MP" level="national" />
              <div className="mt-3">
                <BillVotePanel channelKey="national" scope="national" speakerName={ministers.find(m => m.position === "speaker")?.player_name || setup.speaker_name} winners={winners} partySeats={partySeats} memberLabel="MP" level="national" totalSeats={setup.total_seats} />
              </div>
            </>
          )}
        </>
      ) : (
        <div className="bg-zinc-900 rounded-2xl p-6 border border-zinc-800 text-center">
          <Landmark className="w-10 h-10 text-zinc-600 mx-auto mb-2" />
          <p className="text-sm text-white font-medium">Parliament not created yet</p>
          <p className="text-xs text-zinc-500 mt-1">After the election results and government formation, the admin creates the full parliament screen from Admin → Parliament.</p>
        </div>
      )}
    </div>
  );
}